server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # Page d'accueil par défaut
    location = / {
        return 301 /front/html/accueil.html;
    }

    # Proxy vers l'API backend — évite tout problème CORS
    location /api/ {
        proxy_pass http://chopchopin_api:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Servir les fichiers statiques
    location / {
        try_files $uri $uri/ =404;
    }

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;
}
